spring:
  datasource:
    url: jdbc:mysql://16.16.204.14:3306/foodtrendguide?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    google:
      places:
        api:
          key: AIzaSyCH_tZBEOgtxI2Imc6S-S_BlQWyEZI-YMg